urlMappings:
  - url: http://localhost:8080/hello
    requestParameters: (hello),id
    value:
  - url: http://localhost:8080/hel*
    requestParameters: id
    value: value
  - url: http://localhost:8080/setupFakeData
    requestParameters: id
    value: value