urlMappings:
  - url: http://localhost:8080/hello
    context: clientAppName
    requestParameters: id
    value:
  - url: http://localhost:8080/hel*
    context: clientAppName
    requestParameters: id
    value: value
  - url: http://localhost:8080/setupFakeData
    context: clientAppName
    requestParameters: id
    value: value